spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: "local"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  freemarker:
    cache: 'false'
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'
  datasource:
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    url: ${LOCAL_DB_URL}
    hikari:
      connection-test-query: select 1 from dual
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: govlepel@$&